source 'http://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'thin'
gem 'slim'
gem 'json'
gem 'mongo'
gem 'bson_ext'
gem 'geocoder'
gem 'sinatra-content-for2'
gem 'indextank'
gem 'redcarpet'
gem 'rdiscount'
gem 'kramdown'
gem 'sinatra-flash'